export const courts = [

  // Badminton Courts
  {
    id: 4,
    name: "Shuttle Masters Arena",
    type: "Badminton",
    rating: 4.6,
    reviews: 92,
    price: "₹350/hour",
    image: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1752131924/dexciss%20site/dexplay/optimal/700/badminton_x700/pexels-shvets-production-8007094_x700_vuh3rz.jpg",
    distance: "1.2 km",
    amenities: ["Air Conditioned", "Shower Facilities", "Racket Rental"],
    availability: "5 courts available",
    sports: ["Badminton"],
  },
  {
    id: 5,
    name: "Feathers Badminton Club",
    type: "Badminton",
    rating: 4.4,
    reviews: 67,
    price: "₹300/hour",
    image: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1752131918/dexciss%20site/dexplay/optimal/700/badminton_x700/pexels-shvets-production-8007415_x700_au21db.jpg",
    distance: "2.8 km",
    amenities: ["Coaching Available", "Cafeteria", "Lockers"],
    availability: "Available Now",
    sports: ["Badminton"],
  },
  {
    id: 6,
    name: "Smash City Courts",
    type: "Badminton",
    rating: 4.7,
    reviews: 115,
    price: "₹400/hour",
    image: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1752131922/dexciss%20site/dexplay/optimal/700/badminton_x700/pexels-gordon-ky-331483739-14605729_x700_r1enlt.jpg",
    distance: "3.5 km",
    amenities: ["Premium Courts", "Tournament Ready", "Equipment Shop"],
    availability: "2 courts available",
    sports: ["Badminton"],
  },
  // Cricket Grounds
  {
    id: 7,
    name: "Willow Cricket Park",
    type: "Cricket",
    rating: 4.5,
    reviews: 78,
    price: "₹1500/hour",
    image: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1752131891/dexciss%20site/dexplay/optimal/700/cricket_x700/pexels-aalekh-deval-61079251-9153468_x700_qv8dpj.jpg",
    distance: "4.2 km",
    amenities: ["Turf Pitch", "Pavilion", "Sight Screens"],
    availability: "Available Weekends",
    sports: ["Cricket"],
  },
  {
    id: 8,
    name: "Boundary Field",
    type: "Cricket",
    rating: 4.3,
    reviews: 56,
    price: "₹1200/hour",
    image: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1752131888/dexciss%20site/dexplay/optimal/700/cricket_x700/pexels-kanisha-pari-18647603-6959888_x700_skzjav.jpg",
    distance: "5.1 km",
    amenities: ["Matting Wicket", "Floodlights", "Scorer Available"],
    availability: "Available Now",
    sports: ["Cricket"],
  },
  {
    id: 9,
    name: "Stumps Arena",
    type: "Cricket",
    rating: 4.8,
    reviews: 132,
    price: "₹1800/hour",
    image: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1752131886/dexciss%20site/dexplay/optimal/700/cricket_x700/pexels-noor-zaman-562241425-31739439_x700_okd4mu.jpg",
    distance: "6.3 km",
    amenities: ["Professional Pitch", "Dugouts", "Electronic Scoreboard"],
    availability: "Booking Fast",
    sports: ["Cricket"],
  },
  // Volleyball Courts
  {
    id: 10,
    name: "Spike Zone",
    type: "Volleyball",
    rating: 4.2,
    reviews: 45,
    price: "₹400/hour",
    image: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1752131877/dexciss%20site/dexplay/optimal/700/volleyball_x700/pexels-pavel-danilyuk-6203514_x700_kmcvfc.jpg",
    distance: "2.1 km",
    amenities: ["Sand Court", "Beach Volleyball", "Shower Facilities"],
    availability: "3 courts available",
    sports: ["Volleyball"],
  },
  {
    id: 11,
    name: "Net Masters",
    type: "Volleyball",
    rating: 4.6,
    reviews: 88,
    price: "₹450/hour",
    image: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1752131875/dexciss%20site/dexplay/optimal/700/volleyball_x700/pexels-pavel-danilyuk-6203572_x700_i1zoiu.jpg",
    distance: "3.7 km",
    amenities: ["Indoor Court", "Professional Nets", "Coaching"],
    availability: "Available Now",
    sports: ["Volleyball"],
  },
  {
    id: 12,
    name: "Beach Volley Club",
    type: "Volleyball",
    rating: 4.9,
    reviews: 102,
    price: "₹500/hour",
    image: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1752131871/dexciss%20site/dexplay/optimal/700/volleyball_x700/pexels-kampus-6180389_x700_z3g80d.jpg",
    distance: "5.5 km",
    amenities: ["Beachside Location", "Bar Service", "Night Lighting"],
    availability: "Weekends Only",
    sports: ["Volleyball"],
  },
  // Basketball Courts
  {
    id: 13,
    name: "Hoop Dreams Arena",
    type: "Basketball",
    rating: 4.7,
    reviews: 94,
    price: "₹400/hour",
    image: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1752131856/dexciss%20site/dexplay/optimal/700/basketball_x700/pexels-img_1979-stevonka-379280-2116469_x700_lny9fe.jpg",
    distance: "1.5 km",
    amenities: ["NBA Standard Court", "Scoreboard", "Training Equipment"],
    availability: "Available Now",
    sports: ["Basketball"],
  },
  {
    id: 14,
    name: "Slam Dunk Center",
    type: "Basketball",
    rating: 4.5,
    reviews: 76,
    price: "₹350/hour",
    image: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1752131836/dexciss%20site/dexplay/optimal/700/basketball_x700/pexels-joel-de-leon-227206-934083_x700_dcsdap.jpg",
    distance: "2.9 km",
    amenities: ["Indoor Court", "Pro Shop", "Locker Rooms"],
    availability: "3 courts available",
    sports: ["Basketball"],
  },
  {
    id: 15,
    name: "Urban Basketball Courts",
    type: "Basketball",
    rating: 4.3,
    reviews: 63,
    price: "₹300/hour",
    image: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1752131861/dexciss%20site/dexplay/optimal/700/basketball_x700/pexels-kaip-2234254_x700_z5etjf.jpg",
    distance: "3.4 km",
    amenities: ["Outdoor Court", "Floodlights", "Seating Area"],
    availability: "Open 24/7",
    sports: ["Basketball"],
  },
  // Football Fields
  {
    id: 16,
    name: "Goal Rush Stadium",
    type: "Football",
    rating: 4.8,
    reviews: 142,
    price: "₹1000/hour",
    image: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1752131842/dexciss%20site/dexplay/optimal/700/football_x700/pexels-lucasallmann-1378425_x700_dv2wsu.jpg",
    distance: "4.0 km",
    amenities: ["Full Size Pitch", "Floodlights", "Grandstand"],
    availability: "Booking Required",
    sports: ["Football"],
  },
  {
    id: 17,
    name: "Pitch Perfect Fields",
    type: "Football",
    rating: 4.6,
    reviews: 98,
    price: "₹800/hour",
    image: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1752131829/dexciss%20site/dexplay/optimal/700/football_x700/pexels-bohlemedia-1884576_x700_euwmud.jpg",
    distance: "2.7 km",
    amenities: ["Artificial Turf", "Changing Rooms", "Refreshment Stand"],
    availability: "Available Now",
    sports: ["Football"],
  },
  {
    id: 18,
    name: "The Football Hub",
    type: "Football",
    rating: 4.9,
    reviews: 167,
    price: "₹1200/hour",
    image: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1752131834/dexciss%20site/dexplay/optimal/700/football_x700/pexels-yogendras31-1375148_x700_kvwfos.jpg",
    distance: "5.8 km",
    amenities: ["Multiple Pitches", "Professional Goals", "First Aid"],
    availability: "Weekdays Only",
    sports: ["Football"],
  },
  // Tennis Courts
  {
    id: 19,
    name: "Grand Slam Tennis Club",
    type: "Tennis",
    rating: 4.9,
    reviews: 112,
    price: "₹600/hour",
    image: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1752131865/dexciss%20site/dexplay/optimal/700/tennis_x700/pexels-thinkscotty-2568551_x700_qxokys.jpg",
    distance: "3.1 km",
    amenities: ["Clay Courts", "Ball Machines", "Pro Shop"],
    availability: "Members Only",
    sports: ["Tennis"],
  },
  {
    id: 20,
    name: "Ace Tennis Center",
    type: "Tennis",
    rating: 4.7,
    reviews: 87,
    price: "₹500/hour",
    image: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1752131859/dexciss%20site/dexplay/optimal/700/tennis_x700/pexels-tomfisk-3452545_x700_x0qmfc.jpg",
    distance: "2.3 km",
    amenities: ["Hard Courts", "Floodlights", "Coaching"],
    availability: "4 courts available",
    sports: ["Tennis"],
  },
  {
    id: 21,
    name: "Racket Masters",
    type: "Tennis",
    rating: 4.5,
    reviews: 74,
    price: "₹450/hour",
    image: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1752131857/dexciss%20site/dexplay/optimal/700/tennis_x700/pexels-athena-2961964_x700_ww3c2y.jpg",
    distance: "1.9 km",
    amenities: ["Indoor Courts", "Stringing Service", "Cafe"],
    availability: "Available Now",
    sports: ["Tennis"],
  }
];